<?php

use Illuminate\Database\Seeder;

class SytesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
     // DB::table('テーブル名')->insert(['カラム名' => 'データ']);

    public function run()
    {
        DB::table('sytes')->insert([
            'name' => '天然温泉　スパジアムジャポン',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.spajapo.com/',
            'prefecture' =>'東京都',
            'address' =>'東久留米市上の原2-7-7',
            'nearest' =>'田無駅、東久留米駅、志木駅、朝霞台駅',
            'price' =>'平日750円、休日850円',
            'time' =>'平日午前9時〜深夜１時、休日午前８時〜深夜１時',
            'close' =>'年中無休',
            'bus' =>'あり',
            'direction'=>'Tokyo_West',
            'review'=>'3.5',
            'img1' =>'/img1/spajapo1.jpeg',
            'img2' =>'/img1/spajapo2.jpeg',
        ]);
        DB::table('sytes')->insert([
            
            'name' => '東京新宿天然温泉テルマー湯',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'0',
            'url' => 'https://thermae-yu.jp/',
            'prefecture' =>'東京都',
            'address' =>'新宿区歌舞伎町1-1-2',
            'nearest' =>'新宿駅、新宿三丁目駅',
            'price' =>'平日2405円、休日3285円',
            'time' =>'２４時間営業(深夜追加料金あり)',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Tokyo_East',
            'review'=>'4.5',
            'img1' =>'/img1/teruma1.jpeg',
            'img2' =>'/img1/teruma2.jpeg',
        ]);
        DB::table('sytes')->insert([
          
            'name' => '東京ドーム天然温泉 スパラクーア',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.laqua.jp/spa/',
            'prefecture' =>'東京都',
            'address' =>'文京区春日1-1-1',
            'nearest' =>'後楽園駅、水道橋駅',
            'price' =>'平日2900円、休日3450円',
            'time' =>'午前11時〜翌朝９時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Tokyo_East',
            'review'=>'3.4',
            'img1' =>'/img1/raqua1.jpeg',
            'img2' =>'/img1/raqua2.jpeg',
        ]);
        DB::table('sytes')->insert([
        
            'name' => 'お風呂の王様　花小金井店',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.ousama2603.com/shop/hanakoganei/',
            'prefecture' =>'東京都',
            'address' =>'小平志花小金井金井南町3-9-10',
            'nearest' =>'花小金井駅',
            'price' =>'平日960円、休日1160円',
            'time' =>'午前９時〜午前０時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Tokyo_West',
            'review'=>'4.0',
            'img1' =>'/img1/king1.jpeg',
            'img2' =>'/img1/king2.jpeg',
        ]);
        DB::table('sytes')->insert([
        
            'name' => 'のだ温泉　ほのか',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'0',
            'restaurant' =>'1',
            'url' => 'https://yudokoro-honoka.jp/noda/',
            'prefecture' =>'千葉県',
            'address' =>'野田市花井1-1-2',
            'nearest' =>'梅郷駅',
            'price' =>'平日1400円、休日1600円',
            'time' =>'午前９時〜午前１時',
            'close' =>'年中無休',
            'bus' =>'あり',
            'direction'=>'Chiba_North',
            'review'=>'4.3',
            'img1' =>'/img1/honoka1.jpeg',
            'img2' =>'/img1/honoka2.jpeg',
        ]);
        DB::table('sytes')->insert([
            
            'name' => 'JFA夢フィールド　幕張温泉　湯楽の里',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.yurakirari.com/makuhari/',
            'prefecture' =>'千葉県',
            'address' =>'千葉市美浜区美浜26',
            'nearest' =>'海浜幕張駅',
            'price' =>'平日1050円、平日1300円',
            'time' =>'午前９時〜午前０時',
            'close' =>'年中無休',
            'bus' =>'あり',
            'direction'=>'Chiba_North',
            'review'=>'4.1',
            'img1' =>'/img1/yura1.jpeg',
            'img2' =>'/img1/yura2.jpeg',
        ]);
        DB::table('sytes')->insert([
           
            'name' => 'スパメッツァ おおたか 竜泉寺の湯',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.ryusenjinoyu.com/spametsaotaka/',
            'prefecture' =>'千葉県',
            'address' =>'流山市おおたかの森西1-15-1',
            'nearest' =>'流山おおたかの森駅',
            'price' =>'平日1100円、休日１４８０円',
            'time' =>'午前６時〜午前２時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Chiba_North',
            'review'=>'4.0',
            'img1' =>'/img1/otaka1.jpeg',
            'img2' =>'/img1/otaka2.jpeg',
        ]);
        DB::table('sytes')->insert([
           
            'name' => '南総城山温泉 里見の湯',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.satominoyu.com//',
            'prefecture' =>'千葉県',
            'address' =>'千葉県館山市下真倉305-1',
            'nearest' =>'館山駅',
            'price' =>'平日１２００円、休日１５００円',
            'time' =>'午前１０時〜午後１１時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Chiba_South',
            'review'=>'3.3',
            'img1' =>'/img1/satomi1.jpeg',
            'img2' =>'/img1/satomi2.jpeg',
        ]);
        DB::table('sytes')->insert([
           
            'name' => '綱島源泉 湯けむりの庄',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.yukemurinosato.com/tsunashima/',
            'prefecture' =>'神奈川県',
            'address' =>'横浜市港北区樽町3-7-61',
            'nearest' =>'綱島駅',
            'price' =>'平日１３２０円、休日１５４０円',
            'time' =>'午前９時〜午後１０時',
            'close' =>'年中無休',
            'bus' =>'あり',
            'direction'=>'Kanagawa_East',
            'review'=>'4.1',
            'img1' =>'/img1/yukemuri1.jpeg',
            'img2' =>'/img1/yukemuri2.jpeg',
        ]);
        DB::table('sytes')->insert([
            
            'name' => 'RAKU SPA 鶴見',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.rakuspa.com/tsurumi/',
            'prefecture' =>'神奈川県',
            'address' =>'横浜市鶴見区元宮2-1-39',
            'nearest' =>'川崎駅、鶴見駅',
            'price' =>'平日１９５８円、休日２１７８円',
            'time' =>'平日午前１０時〜午前２時、休日午前１０時〜午前８時',
            'close' =>'年中無休',
            'bus' =>'あり',
            'direction'=>'Kanagawa_East',
            'review'=>'3.9',
            'img1' =>'/img1/turumi1.jpeg',
            'img2' =>'/img1/turumi2.jpeg',
        ]);
        DB::table('sytes')->insert([
            
            'name' => '横濱スパヒルズ 竜泉寺の湯',
            'sauna' => '0',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'0',
            'url' => 'https://tsurugamine.ryusenjinoyu.com/',
            'prefecture' =>'神奈川県',
            'address' =>'横浜市旭区城根8-8',
            'nearest' =>'西谷駅、鴨居駅',
            'price' =>'平日７５０円、休日８５０円',
            'time' =>'午前６時〜午前１時',
            'close' =>'年中無休',
            'bus' =>'あり',
            'direction'=>'Kanagawa_East',
            'review'=>'4.0',
            'img1' =>'/img1/yokohama1.jpeg',
            'img2' =>'/img1/yokohama2.jpeg',
        ]);
        DB::table('sytes')->insert([
          
            'name' => '箱根湯寮',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'0',
            'restaurant' =>'1',
            'url' => 'https://www.hakoneyuryo.jp/',
            'prefecture' =>'神奈川県',
            'address' =>'足柄下郡箱根町塔之澤4',
            'nearest' =>'箱根湯本駅',
            'price' =>'平日１５００円、休日１８００円',
            'time' =>'平日午前１０時〜午後８時、休日午前１０時〜午後９時',
            'close' =>'年中無休(メンテナンスにより休館あり)',
            'bus' =>'あり',
            'direction'=>'Kanagawa_West',
            'review'=>'3.6',
            'img1' =>'/img1/hakone1.jpeg',
            'img2' =>'/img1/hakone2.jpeg',
        ]);
        DB::table('sytes')->insert([
      
            'name' => '西武秩父駅前温泉　祭りの湯',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.seibu-leisure.co.jp/matsuri/index.html',
            'prefecture' =>'埼玉県',
            'address' =>'秩父市野坂町1-16-15',
            'nearest' =>'西武秩父駅、御花畑駅',
            'price' =>'平日９９０円、休日１１００円',
            'time' =>'午前１０時〜午後１０時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Saitama_Eest',
            'review'=>'3.6',
            'img1' =>'/img1/maturi1.jpeg',
            'img2' =>'/img1/maturi2.jpeg',
        ]);
        DB::table('sytes')->insert([
       
            'name' => '美楽温泉　SPA-HERBS',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://spa-herbs.jp/',
            'prefecture' =>'埼玉県',
            'address' =>'さいたま市北区植竹町1-816-8',
            'nearest' =>'大宮駅、土呂駅',
            'price' =>'平日９５０円、休日１１５０円',
            'time' =>'午前９時〜午前０時',
            'close' =>'年中無休',
            'bus' =>'あり',
            'direction'=>'Saitama_East',
            'review'=>'4.6',
            'img1' =>'/img1/herbs1.jpeg',
            'img2' =>'/img1/herbs2.jpeg',
        ]);
        DB::table('sytes')->insert([
         
            'name' => '熊谷天然温泉花湯スパリゾート',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'http://hanayuspa.jp/',
            'prefecture' =>'埼玉県',
            'address' =>'熊谷市上之1005',
            'nearest' =>'',
            'price' =>'',
            'time' =>'',
            'close' =>'',
            'bus' =>'',
            'direction'=>'Saitama_West',
            'review'=>'4.5',
            'img1' =>'/img1/kumagaya1.jpeg',
            'img2' =>'/img1/kumagaya2.jpeg',
        ]);
        DB::table('sytes')->insert([
          
            'name' => '秩父温泉　満願の湯',
            'sauna' => '1',
            'ganban' => '0',
            'tansan' =>'0',
            'restaurant' =>'1',
            'url' => 'https://www.chichibuonsen.co.jp/',
            'prefecture' =>'埼玉県',
            'address' =>'秩父郡皆野町下日野沢4000',
            'nearest' =>'皆野駅',
            'price' =>'平日８５０円、休日１０００円',
            'time' =>'午前１０時～午後９時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Saitama_West',
            'review'=>'3.4',
            'img1' =>'/img1/mangan1.jpeg',
            'img2' =>'/img1/mangan2.jpeg',
        ]);
        DB::table('sytes')->insert([
          
            'name' => '黄金の湯館',
            'sauna' => '1',
            'ganban' => '0',
            'tansan' =>'0',
            'restaurant' =>'1',
            'url' => 'https://www.itoenhotel.com/koganenoyu/',
            'prefecture' =>'群馬県',
            'address' =>'渋川市伊香保町伊香保550',
            'nearest' =>'渋川駅',
            'price' =>'１５時までの受付で６８０円、１５時以降受付９８０円',
            'time' =>'午前１０時〜午前０時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Gunma_North',
            'review'=>'3.7',
            'img1' =>'/img1/kogane1.jpeg',
            'img2' =>'/img1/kogane2.jpeg',
        ]);
        DB::table('sytes')->insert([
           
            'name' => '西の河原露天風呂',
            'sauna' => '0',
            'ganban' => '0',
            'tansan' =>'0',
            'restaurant' =>'0',
            'url' => 'http://sainokawara.com/',
            'prefecture' =>'群馬県',
            'address' =>'吾妻郡草津町草津521-3',
            'nearest' =>'草津駅',
            'price' =>'全日７００円',
            'time' =>'午前９時〜午後２０時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Gunma_North',
            'review'=>'4.1',
            'img1' =>'/img1/kawara1.jpeg',
            'img2' =>'/img1/kawara2.jpeg',
        ]);
        DB::table('sytes')->insert([
           
            'name' => '京ヶ島天然温泉　湯都里',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'0',
            'restaurant' =>'1',
            'url' => 'https://www.yu-tori.jp/',
            'prefecture' =>'群馬県',
            'address' =>'高崎市島野町890-3',
            'nearest' =>'高崎駅',
            'price' =>'平日９８０円、休日１１８０円',
            'time' =>'午前５時〜午前０時まで',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Gunma_South',
            'review'=>'4.1',
            'img1' =>'/img1/yutori1.jpeg',
            'img2' =>'/img1/yutori2.jpeg',
        ]);
        DB::table('sytes')->insert([

            'name' => '湯楽部　太田店',
            'sauna' => '1',
            'ganban' => '0',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://ota.yurabu.com/',
            'prefecture' =>'群馬県',
            'address' =>'太田市植木野町694-1',
            'nearest' =>'韮川駅(にらがわえき)',
            'price' =>'平日１１８０円、休日１３３０円',
            'time' =>'午前１０時〜午前０時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Gunma_South',
            'review'=>'3.8',
            'img1' =>'/img1/yurabu1.jpeg',
            'img2' =>'/img1/yurabu2.jpeg',
        ]);
        DB::table('sytes')->insert([
       
            'name' => '栃木温泉由良の里',
            'sauna' => '1',
            'ganban' => '0',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.yurakirari.com/yura/tochigi/',
            'prefecture' =>'栃木県',
            'address' =>'栃木市大町22-70',
            'nearest' =>'新栃木駅',
            'price' =>'平日８２０円、休日９２０円',
            'time' =>'午前８時３０分〜午前２４時',
            'close' =>'年中無休',
            'bus' =>'あり',
            'direction'=>'Tochigi_South',
            'review'=>'4.2',
            'img1' =>'/img1/tochigi1.jpeg',
            'img2' =>'/img1/tochigi2.jpeg',
        ]);
        DB::table('sytes')->insert([
          
            'name' => '宮の街道温泉 江戸遊',
            'sauna' => '0',
            'ganban' => '0',
            'tansan' =>'0',
            'restaurant' =>'1',
            'url' => 'https://www.edoyu.com/utsunomiya/',
            'prefecture' =>'栃木県',
            'address' =>'宇都宮市インターパーク4-2-5',
            'nearest' =>'宇都宮',
            'price' =>'全日１３８０円',
            'time' =>'午前９時〜午前０時',
            'close' =>'年中無休',
            'bus' =>'あり',
            'direction'=>'Tochigi_South',
            'review'=>'4.5',
            'img1' =>'/img1/edo1.jpeg',
            'img2' =>'/img1/edo2.jpeg',
        ]);
        DB::table('sytes')->insert([
          
            'name' => 'ベルさくらの湯',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'0',
            'restaurant' =>'1',
            'url' => 'https://bellsakuranoyu.com/',
            'prefecture' =>'栃木県',
            'address' =>'宇都宮市陽東6-5-31',
            'nearest' =>'宇都宮駅',
            'price' =>'平日１３００円、休日１４００円',
            'time' =>'午前８時〜午後１１時',
            'close' =>'毎月第３月曜日',
            'bus' =>'なし',
            'direction'=>'Tochigi_South',
            'review'=>'3.7',
            'img1' =>'/img1/beru1.jpeg',
            'img2' =>'/img1/beru2.jpeg',
        ]);
        DB::table('sytes')->insert([
            
            'name' => '自然浴 離れの湯 あけび',
            'sauna' => '0',
            'ganban' => '0',
            'tansan' =>'0',
            'restaurant' =>'0',
            'url' => 'akebi-onsen.com',
            'prefecture' =>'栃木県',
            'address' =>'日光市小佐越原19-26',
            'nearest' =>'鬼怒川温泉駅',
            'price' =>'時間制のため、ホームページ参照',
            'time' =>'午前１０時〜午後１１時',
            'close' =>'不定休',
            'bus' =>'なし',
            'direction'=>'Tochigi_North',
            'review'=>'4.4',
            'img1' =>'/img1/akebi1.jpeg',
            'img2' =>'/img1/akebi2.jpeg',
        ]);
        DB::table('sytes')->insert([
       
            'name' => 'ひたちなか温泉　喜楽里　別邸',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.yurakirari.com/kirari/hitachinaka/',
            'prefecture' =>'茨城県',
            'address' =>'ひたちなか市市毛640-2',
            'nearest' =>'水戸駅、勝田駅',
            'price' =>'平日１２９０円、休日１４５０円',
            'time' =>'午前８時〜午後１１時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Ibaraki_North',
            'review'=>'4.7',
            'img1' =>'/img1/kirari1.jpeg',
            'img2' =>'/img1/kirari2.jpeg',
        ]);
        DB::table('sytes')->insert([
            
            'name' => '湯楽の里 日立店',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.yurakirari.com/yura/hitachi/',
            'prefecture' =>'茨城県',
            'address' =>'日立市河原子町1-1-6',
            'nearest' =>'常陸多賀駅',
            'price' =>'平日８００円、休日９００円',
            'time' =>'午前９時〜午前１時',
            'close' =>'年中無休',
            'bus' =>'なし',
            'direction'=>'Ibaraki_North',
            'review'=>'4.4',
            'img1' =>'/img1/hitati1.jpeg',
            'img2' =>'/img1/hitati2.jpeg',
        ]);
        DB::table('sytes')->insert([
           
            'name' => 'きぬの湯',
            'sauna' => '1',
            'ganban' => '0',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.kinunoyu.com/',
            'prefecture' =>'茨城県',
            'address' =>'常総市内守谷町きぬの里1-5-6',
            'nearest' =>'守谷駅',
            'price' =>'午前９時〜午後１１時',
            'time' =>'平日１５００円、休日１６００円',
            'close' =>'毎週水曜日',
            'bus' =>'なし',
            'direction'=>'Ibaraki_South',
            'review'=>'4.0',
            'img1' =>'/img1/kinu1.jpeg',
            'img2' =>'/img1/kinu2.jpeg',
        ]);
        DB::table('sytes')->insert([
            
            'name' => '岩盤温浴リゾート　ココプララ',
            'sauna' => '1',
            'ganban' => '1',
            'tansan' =>'1',
            'restaurant' =>'1',
            'url' => 'https://www.cocoplala.jp/',
            'prefecture' =>'茨城県',
            'address' =>'東茨城郡茨城町桜の郷1100',
            'nearest' =>'水戸駅、赤塚駅',
            'price' =>'平日１３８０円、休日１４８０円',
            'time' =>'午前９時〜午後１１時',
            'close' =>'毎週月曜日、元旦',
            'bus' =>'なし',
            'direction'=>'Ibaraki_North',
            'review'=>'4.5',
            'img1' =>'/img1/koko1.jpeg',
            'img2' =>'/img/koko2.jpeg',
        ]);
    }
}
